import { ArchetypeId } from '../utils/archetypes';

export interface ArchetypeContent {
  id: ArchetypeId;
  name_en: string;
  name_pl: string;
  short_hook_en: string;
  short_hook_pl: string;
  first_signal_en: string;
  first_signal_pl: string;
  core_drive_en: string;
  core_drive_pl: string;
  strength_en: string;
  strength_pl: string;
  shadow_en: string;
  shadow_pl: string;
  under_pressure_en: string;
  under_pressure_pl: string;
  work_pattern_en: string;
  work_pattern_pl: string;
  relationship_pattern_en: string;
  relationship_pattern_pl: string;
  hidden_fear_en: string;
  hidden_fear_pl: string;
  premium_teaser_en: string;
  premium_teaser_pl: string;
}

export const ARCHETYPE_CONTENT: Record<ArchetypeId, ArchetypeContent> = {
  explorer: {
    id: 'explorer',
    name_en: 'The Explorer',
    name_pl: 'Odkrywca',
    short_hook_en: 'You are not running away. You are running toward — and you need people to understand the difference.',
    short_hook_pl: 'Nie uciekasz. Biegniesz w stronę czegoś — i potrzebujesz, żeby ludzie rozumieli tę różnicę.',
    first_signal_en: 'You noticed three exits before you sat down.',
    first_signal_pl: 'Zauważyłeś trzy wyjścia, zanim usiadłeś.',
    core_drive_en: 'The world is larger than your current life, and this bothers you.',
    core_drive_pl: 'Świat jest większy niż twoje obecne życie i to cię niepokoi.',
    strength_en: 'You see possibility in situations where most people only see risk or repetition.',
    strength_pl: 'Widzisz możliwości tam, gdzie inni widzą tylko ryzyko lub powtarzalność.',
    shadow_en: 'You leave before things get complicated — and call it freedom.',
    shadow_pl: 'Odchodzisz, zanim sprawy się skomplikują — i nazywasz to wolnością.',
    under_pressure_en: 'You start a new project. Not to escape, you tell yourself. Just because this one is genuinely interesting.',
    under_pressure_pl: 'Zaczynasz nowy projekt. Nie po to, żeby uciec, mówisz sobie. Po prostu ten jest naprawdę interesujący.',
    work_pattern_en: 'Brilliant in early stages. A liability in the maintenance phase.',
    work_pattern_pl: 'Błyskotliwy w początkowych fazach. Problematyczny w fazie utrzymania.',
    relationship_pattern_en: 'You are great at beginning things. The people in your life know this about you.',
    relationship_pattern_pl: 'Jesteś dobry w zaczynaniu rzeczy. Ludzie w twoim życiu o tym wiedzą.',
    hidden_fear_en: 'That settling down would finally reveal whether you were running toward something or away from it.',
    hidden_fear_pl: 'Że osiedlenie się w końcu ujawni, czy biegłeś ku czemuś, czy od czegoś.',
    premium_teaser_en: 'Your full profile shows which 3 of your 10 axes create your specific movement pattern — and when it works against you.',
    premium_teaser_pl: 'Twój pełny profil pokazuje, które 3 z 10 osi tworzą twój specyficzny wzorzec ruchu — i kiedy działa przeciwko tobie.',
  },

  architect: {
    id: 'architect',
    name_en: 'The Architect',
    name_pl: 'Architekt',
    short_hook_en: 'You do not have trust issues. You have evidence.',
    short_hook_pl: 'Nie masz problemów z zaufaniem. Masz dowody.',
    first_signal_en: 'You already know what will go wrong with this plan.',
    first_signal_pl: 'Już wiesz, co pójdzie nie tak z tym planem.',
    core_drive_en: 'Things should work correctly. Most things do not, and this is a personal problem for you.',
    core_drive_pl: 'Rzeczy powinny działać poprawnie. Większość nie działa, i jest to dla ciebie osobisty problem.',
    strength_en: 'You build things that outlast the enthusiasm that started them.',
    strength_pl: 'Budujesz rzeczy, które przeżywają entuzjazm, który je zapoczątkował.',
    shadow_en: 'You mistake perfection of process for completion of purpose.',
    shadow_pl: 'Mylisz doskonałość procesu z osiągnięciem celu.',
    under_pressure_en: 'You create a more detailed system. The problem is usually not a lack of detail.',
    under_pressure_pl: 'Tworzysz bardziej szczegółowy system. Problem zazwyczaj nie polega na braku szczegółów.',
    work_pattern_en: 'Produces work with a long shelf life. Terrible at shipping things that are 80% ready.',
    work_pattern_pl: 'Tworzy pracę z długim terminem ważności. Fatalny przy wysyłaniu rzeczy gotowych w 80%.',
    relationship_pattern_en: 'You show love through reliability. This is not always what people ask for.',
    relationship_pattern_pl: 'Wyrażasz miłość przez niezawodność. Nie zawsze o to ludzie proszą.',
    hidden_fear_en: 'That you will optimize your life so thoroughly you forget to live it.',
    hidden_fear_pl: 'Że tak dokładnie zoptymalizujesz swoje życie, że zapomnisz je przeżyć.',
    premium_teaser_en: 'Your profile reveals which axis creates your specific relationship between control and trust.',
    premium_teaser_pl: 'Twój profil ujawnia, która oś tworzy twój specyficzny związek między kontrolą a zaufaniem.',
  },

  rebel: {
    id: 'rebel',
    name_en: 'The Rebel',
    name_pl: 'Buntownik',
    short_hook_en: 'You are not difficult. You are calibrated to something most people cannot see yet.',
    short_hook_pl: 'Nie jesteś trudny. Jesteś skalibrowany na coś, czego większość ludzi jeszcze nie widzi.',
    first_signal_en: 'You have already identified the flaw in the system that no one else is talking about.',
    first_signal_pl: 'Już zidentyfikowałeś błąd w systemie, o którym nikt nie mówi.',
    core_drive_en: 'Things that should not exist should be made to not exist.',
    core_drive_pl: 'Rzeczy, które nie powinny istnieć, powinny przestać istnieć.',
    strength_en: 'You say the thing everyone agreed not to say.',
    strength_pl: 'Mówisz to, na co wszyscy się milcząco zgodzili milczeć.',
    shadow_en: 'You oppose things reflexively — including things worth keeping.',
    shadow_pl: 'Sprzeciwiasz się rzeczom odruchowo — łącznie z tymi, które warto zachować.',
    under_pressure_en: 'You escalate. The argument gets louder. You become the problem.',
    under_pressure_pl: 'Eskalujesz. Kłótnia się nasila. Stajesz się problemem.',
    work_pattern_en: 'Extraordinary at the start and at the end. Does not stay for the middle.',
    work_pattern_pl: 'Nadzwyczajny na początku i na końcu. Nie zostaje na środek.',
    relationship_pattern_en: 'Intensely loyal to the few who earn it. Invisible to everyone else.',
    relationship_pattern_pl: 'Intensywnie lojalny wobec nielicznych, którzy na to zasłużyli. Niewidoczny dla wszystkich innych.',
    hidden_fear_en: 'That your need to oppose is itself a form of control — by something you cannot name.',
    hidden_fear_pl: 'Że twoja potrzeba sprzeciwu jest sama w sobie formą kontroli — przez coś, czego nie możesz nazwać.',
    premium_teaser_en: 'Your profile shows which axis is a genuine strength and which one is armor you forgot you put on.',
    premium_teaser_pl: 'Twój profil pokazuje, która oś jest prawdziwą siłą, a która jest zbroją, o której zapomniałeś, że ją założyłeś.',
  },

  guardian: {
    id: 'guardian',
    name_en: 'The Guardian',
    name_pl: 'Strażnik',
    short_hook_en: 'You are not afraid of change. You are afraid of what gets lost in it.',
    short_hook_pl: 'Nie boisz się zmian. Boisz się tego, co w nich ginie.',
    first_signal_en: 'You already have a backup plan for the backup plan.',
    first_signal_pl: 'Masz już plan awaryjny dla planu awaryjnego.',
    core_drive_en: 'What matters should be protected. You are the one who makes sure it is.',
    core_drive_pl: 'To, co ważne, powinno być chronione. Ty dopilnowujesz, żeby tak było.',
    strength_en: 'You hold the center while everyone else experiments with leaving it.',
    strength_pl: 'Trzymasz centrum, podczas gdy wszyscy inni eksperymentują z jego opuszczaniem.',
    shadow_en: 'You protect things past the point where they needed protecting.',
    shadow_pl: 'Chronisz rzeczy długo po tym, gdy przestały wymagać ochrony.',
    under_pressure_en: 'You tighten your grip. You become more rule-bound. You feel like the only responsible one in the room.',
    under_pressure_pl: 'Zaciskasz uchwyt. Stajesz się bardziej związany regułami. Czujesz się jedyną odpowiedzialną osobą w pokoju.',
    work_pattern_en: 'Irreplaceable in continuity. Difficult to have around when the organization needs to change.',
    work_pattern_pl: 'Niezastąpiony w ciągłości. Trudny do utrzymania, gdy organizacja potrzebuje się zmienić.',
    relationship_pattern_en: 'You are the person people call in a crisis. This is not always comfortable.',
    relationship_pattern_pl: 'Jesteś osobą, do której dzwonią w kryzysie. To nie zawsze jest wygodne.',
    hidden_fear_en: 'That the things you have been protecting no longer need you to protect them.',
    hidden_fear_pl: 'Że rzeczy, które chroniłeś, już cię nie potrzebują.',
    premium_teaser_en: 'Your profile shows which axis makes you protective and which one makes you controlling — and the space between them.',
    premium_teaser_pl: 'Twój profil pokazuje, która oś czyni cię opiekuńczym, a która kontrolującym — i przestrzeń między nimi.',
  },

  mirror: {
    id: 'mirror',
    name_en: 'The Mirror',
    name_pl: 'Lustro',
    short_hook_en: 'You understand people better than they understand themselves. This is useful and exhausting.',
    short_hook_pl: 'Rozumiesz ludzi lepiej niż oni sami siebie rozumieją. To przydatne i wyczerpujące.',
    first_signal_en: 'You adjusted your energy the moment you walked into the room.',
    first_signal_pl: 'Dostosowałeś swoją energię w chwili, gdy wszedłeś do pokoju.',
    core_drive_en: 'You want to understand what it is actually like to be someone else.',
    core_drive_pl: 'Chcesz zrozumieć, jakie to naprawdę jest być kimś innym.',
    strength_en: 'You see people clearly, including the parts they are hiding from themselves.',
    strength_pl: 'Widzisz ludzi wyraźnie, łącznie z częściami, które sami przed sobą ukrywają.',
    shadow_en: 'You can lose yourself in understanding others and forget to have a position of your own.',
    shadow_pl: 'Możesz zatracić siebie w rozumieniu innych i zapomnieć mieć własne stanowisko.',
    under_pressure_en: 'You become a version of what everyone around you needs. You stop knowing which one is you.',
    under_pressure_pl: 'Stajesz się wersją tego, czego potrzebuje każdy wokół ciebie. Przestajesz wiedzieć, która wersja to ty.',
    work_pattern_en: 'Exceptional in roles requiring human understanding. Quietly exhausted by them.',
    work_pattern_pl: 'Wyjątkowy w rolach wymagających rozumienia ludzi. Cicho wyczerpany przez nie.',
    relationship_pattern_en: 'People feel seen by you in a way they cannot explain. This creates both closeness and dependency.',
    relationship_pattern_pl: 'Ludzie czują się przez ciebie zauważeni w sposób, którego nie potrafią wyjaśnić. To tworzy zarówno bliskość, jak i zależność.',
    hidden_fear_en: 'That you are so good at reflecting others that there is nothing left when they leave.',
    hidden_fear_pl: 'Że jesteś tak dobry w odzwierciedlaniu innych, że nic nie zostaje, gdy odejdą.',
    premium_teaser_en: 'Your profile shows where your empathy is a skill and where it is a survival strategy you adopted long ago.',
    premium_teaser_pl: 'Twój profil pokazuje, gdzie twoja empatia jest umiejętnością, a gdzie strategią przetrwania, którą przyjąłeś dawno temu.',
  },

  strategist: {
    id: 'strategist',
    name_en: 'The Strategist',
    name_pl: 'Strateg',
    short_hook_en: 'You are not cold. You operate at a frequency most people do not broadcast on.',
    short_hook_pl: 'Nie jesteś zimny. Operujesz na częstotliwości, na której większość ludzi nie nadaje.',
    first_signal_en: 'You calculated three moves ahead before the meeting started.',
    first_signal_pl: 'Obliczyłeś trzy ruchy do przodu, zanim zaczęło się spotkanie.',
    core_drive_en: 'Every system has an optimal version. Finding it is not optional.',
    core_drive_pl: 'Każdy system ma optymalną wersję. Znalezienie jej nie jest opcjonalne.',
    strength_en: 'You see the structure underneath the chaos and know exactly which lever to pull.',
    strength_pl: 'Widzisz strukturę pod chaosem i wiesz dokładnie, którą dźwignię pociągnąć.',
    shadow_en: 'You optimize things that were never meant to be optimized.',
    shadow_pl: 'Optymalizujesz rzeczy, które nigdy nie miały być optymalizowane.',
    under_pressure_en: 'You go quiet. You compute. You come back with a plan that is correct and arrives too late.',
    under_pressure_pl: 'Milkniesz. Analizujesz. Wracasz z planem, który jest poprawny i przybywa za późno.',
    work_pattern_en: 'Decisive and scalable. Loses the colleagues who cannot follow the logic.',
    work_pattern_pl: 'Decyzyjny i skalowalny. Traci współpracowników, którzy nie mogą podążać za logiką.',
    relationship_pattern_en: 'You are reliable. You are not always warm. People confuse these two things.',
    relationship_pattern_pl: 'Jesteś niezawodny. Nie zawsze jesteś ciepły. Ludzie mylą te dwie rzeczy.',
    hidden_fear_en: 'That the most important things cannot be optimized — and you do not know what to do with them.',
    hidden_fear_pl: 'Że najważniejsze rzeczy nie mogą być zoptymalizowane — i nie wiesz, co z nimi zrobić.',
    premium_teaser_en: 'Your profile shows the specific axis where your strategic clarity is an asset and where it becomes a wall.',
    premium_teaser_pl: 'Twój profil pokazuje konkretną oś, gdzie twoja strategiczna jasność jest atutem, a gdzie staje się murem.',
  },

  weaver: {
    id: 'weaver',
    name_en: 'The Weaver',
    name_pl: 'Tkacz',
    short_hook_en: 'You are not indecisive. You are protecting several versions of your future at once.',
    short_hook_pl: 'Nie jesteś niezdecydowany. Chronisz kilka wersji swojej przyszłości jednocześnie.',
    first_signal_en: 'You have a notebook full of beginnings.',
    first_signal_pl: 'Masz notatnik pełen początków.',
    core_drive_en: 'There is a version of life that would feel completely right — and you have not found it yet.',
    core_drive_pl: 'Istnieje wersja życia, która czułaby się zupełnie słuszna — i jeszcze jej nie znalazłeś.',
    strength_en: 'You hold open possibilities that others close too quickly.',
    strength_pl: 'Utrzymujesz otwarte możliwości, które inni zamykają zbyt szybko.',
    shadow_en: 'You are so oriented toward what could be that you miss what is.',
    shadow_pl: 'Jesteś tak skupiony na tym, co mogłoby być, że przegapiasz to, co jest.',
    under_pressure_en: 'You become unreachable. Not geographically — just somehow not quite there.',
    under_pressure_pl: 'Stajesz się nieosiągalny. Nie geograficznie — po prostu jakoś nie do końca tu jesteś.',
    work_pattern_en: 'Visionary who needs translators. Ideas arrive complete. Execution arrives eventually.',
    work_pattern_pl: 'Wizjoner, który potrzebuje tłumaczy. Pomysły przychodzą gotowe. Realizacja — w końcu.',
    relationship_pattern_en: 'People fall in love with your potential. This is not always fair to either of you.',
    relationship_pattern_pl: 'Ludzie zakochują się w twoim potencjale. To nie zawsze jest fair dla żadnej ze stron.',
    hidden_fear_en: 'That when you finally stop searching, you will find it was never about the destination.',
    hidden_fear_pl: 'Że kiedy w końcu przestaniesz szukać, odkryjesz, że nigdy nie chodziło o cel.',
    premium_teaser_en: 'Your profile shows what you are actually seeking — and why you keep moving the goalpost.',
    premium_teaser_pl: 'Twój profil pokazuje, czego naprawdę szukasz — i dlaczego ciągle przesuwasz linię mety.',
  },

  anchor: {
    id: 'anchor',
    name_en: 'The Anchor',
    name_pl: 'Kotwica',
    short_hook_en: 'You want freedom, but you secretly want someone to notice when you disappear.',
    short_hook_pl: 'Chcesz wolności, ale w tajemnicy chcesz, żeby ktoś zauważył, gdy znikasz.',
    first_signal_en: 'You checked on someone else before you addressed your own problem.',
    first_signal_pl: 'Sprawdziłeś kogoś innego, zanim zająłeś się własnym problemem.',
    core_drive_en: 'People should feel safe. You are willing to make yourself smaller to make that happen.',
    core_drive_pl: 'Ludzie powinni czuć się bezpiecznie. Jesteś gotów stać się mniejszy, żeby to się stało.',
    strength_en: 'You hold groups together in ways no one sees until you are gone.',
    strength_pl: 'Trzymasz grupy razem w sposób, którego nikt nie widzi, dopóki cię nie ma.',
    shadow_en: 'You give more than you have, and you do it quietly until you cannot.',
    shadow_pl: 'Dajesz więcej niż masz, i robisz to po cichu, aż nie możesz dłużej.',
    under_pressure_en: 'You become invisible. You accommodate. You wonder why no one asks how you are.',
    under_pressure_pl: 'Stajesz się niewidoczny. Stosujesz się do sytuacji. Zastanawiasz się, czemu nikt nie pyta, jak ty się masz.',
    work_pattern_en: 'The person the team could not function without. Rarely the person who gets credit for it.',
    work_pattern_pl: 'Osoba, bez której zespół nie mógłby funkcjonować. Rzadko ta, która dostaje za to uznanie.',
    relationship_pattern_en: 'You love deeply and carry it privately. The people you love often underestimate this.',
    relationship_pattern_pl: 'Kochasz głęboko i nosisz to w sobie prywatnie. Ludzie, których kochasz, często to niedoceniają.',
    hidden_fear_en: 'That if you stopped holding things together, nothing would fall — and that would mean it was never about them.',
    hidden_fear_pl: 'Że jeśli przestałbyś trzymać wszystko razem, nic by nie runęło — i to oznaczałoby, że nigdy nie chodziło o nich.',
    premium_teaser_en: 'Your profile shows the axis where your care for others is a genuine gift and the one where it is a cost you do not count.',
    premium_teaser_pl: 'Twój profil pokazuje oś, gdzie troska o innych jest prawdziwym darem, i tę, gdzie jest kosztem, którego nie liczysz.',
  },

  catalyst: {
    id: 'catalyst',
    name_en: 'The Catalyst',
    name_pl: 'Iskra',
    short_hook_en: 'You often look calm because you already panicked internally.',
    short_hook_pl: 'Często wyglądasz spokojnie, bo już wpadłeś w panikę wewnętrznie.',
    first_signal_en: 'You sent the message before you thought through the consequences.',
    first_signal_pl: 'Wysłałeś wiadomość, zanim przemyślałeś konsekwencje.',
    core_drive_en: 'Things that need to move should move. You make them move.',
    core_drive_pl: 'Rzeczy, które muszą się ruszyć, powinny się ruszyć. Ty je ruszasz.',
    strength_en: 'You create momentum where there was none. People find this magnetic.',
    strength_pl: 'Tworzysz pęd tam, gdzie go nie było. Ludzie uważają to za magnetyczne.',
    shadow_en: 'You change direction mid-process and expect everyone to follow without warning.',
    shadow_pl: 'Zmieniasz kierunek w trakcie procesu i oczekujesz, że wszyscy pójdą za tobą bez ostrzeżenia.',
    under_pressure_en: 'You act. Quickly. The action is not always the right one.',
    under_pressure_pl: 'Działasz. Szybko. Działanie nie zawsze jest właściwe.',
    work_pattern_en: 'Extraordinary at initiation. Not available for the long middle.',
    work_pattern_pl: 'Nadzwyczajny przy inicjowaniu. Niedostępny dla długiego środka.',
    relationship_pattern_en: 'People remember meeting you. Sustaining connection over time is harder.',
    relationship_pattern_pl: 'Ludzie pamiętają, jak cię poznali. Podtrzymanie połączenia w czasie jest trudniejsze.',
    hidden_fear_en: 'That if you stop moving, you will have to sit with what you are when nothing is happening.',
    hidden_fear_pl: 'Że jeśli przestaniesz się ruszać, będziesz musiał siedzieć z tym, czym jesteś, gdy nic się nie dzieje.',
    premium_teaser_en: 'Your profile shows what you are actually igniting — and whether the fire is where you intended it.',
    premium_teaser_pl: 'Twój profil pokazuje, co naprawdę zapłaniesz — i czy ogień jest tam, gdzie zamierzałeś.',
  },

  observer: {
    id: 'observer',
    name_en: 'The Observer',
    name_pl: 'Obserwator',
    short_hook_en: 'You see everything. This is not always comfortable for you or for the people you observe.',
    short_hook_pl: 'Widzisz wszystko. To nie zawsze jest wygodne dla ciebie ani dla ludzi, których obserwujesz.',
    first_signal_en: 'You knew something was wrong three weeks before anyone said it out loud.',
    first_signal_pl: 'Wiedziałeś, że coś jest nie tak trzy tygodnie przed tym, zanim ktokolwiek to powiedział na głos.',
    core_drive_en: 'Understanding something completely is different from understanding it enough to act.',
    core_drive_pl: 'Zrozumieć coś całkowicie różni się od zrozumienia tego na tyle, żeby działać.',
    strength_en: 'You process what others scan. This gives you a different kind of accuracy.',
    strength_pl: 'Przetwarzasz to, co inni skanują. To daje ci inny rodzaj dokładności.',
    shadow_en: 'You watch until it is too late to enter.',
    shadow_pl: 'Obserwujesz, aż jest za późno, żeby wejść.',
    under_pressure_en: 'You retreat into analysis. The analysis is usually correct. The timing is not.',
    under_pressure_pl: 'Cofasz się w analizę. Analiza jest zazwyczaj poprawna. Timing — nie.',
    work_pattern_en: 'Invaluable in diagnosis. Slow at shipping. Rarely wrong in the long run.',
    work_pattern_pl: 'Bezcenny w diagnozie. Wolny przy dostarczaniu. Rzadko myli się na dłuższą metę.',
    relationship_pattern_en: 'People feel understood by you, but not always reached. There is a difference.',
    relationship_pattern_pl: 'Ludzie czują się przez ciebie rozumiani, ale nie zawsze dotknięci. Jest różnica.',
    hidden_fear_en: 'That the life you have been carefully observing will end before you decided to participate in it.',
    hidden_fear_pl: 'Że życie, które uważnie obserwowałeś, skończy się, zanim zdecydujesz się w nim uczestniczyć.',
    premium_teaser_en: 'Your profile shows the specific gap between your perception and your participation — and what lives in that space.',
    premium_teaser_pl: 'Twój profil pokazuje konkretną lukę między twoją percepcją a uczestnictwem — i to, co tam mieszka.',
  },

  alchemist: {
    id: 'alchemist',
    name_en: 'The Alchemist',
    name_pl: 'Alchemik',
    short_hook_en: 'You do not work with what you have. You work with what you can see it becoming.',
    short_hook_pl: 'Nie pracujesz z tym, co masz. Pracujesz z tym, czym to może się stać.',
    first_signal_en: 'You cannot look at something broken without imagining what it could be turned into.',
    first_signal_pl: 'Nie możesz patrzeć na coś zepsutego bez wyobrażania sobie, w co można to zamienić.',
    core_drive_en: 'Everything has a better form. You are trying to find it.',
    core_drive_pl: 'Wszystko ma lepszą formę. Starasz się ją znaleźć.',
    strength_en: 'You make connections between things that have no business being connected. They work.',
    strength_pl: 'Łączysz rzeczy, które nie mają ze sobą nic wspólnego. To działa.',
    shadow_en: 'You chase the transformation more than the thing being transformed.',
    shadow_pl: 'Ścigasz transformację bardziej niż transformowaną rzecz.',
    under_pressure_en: 'You fragment. Three half-finished things where there should be one completed one.',
    under_pressure_pl: 'Fragmentujesz. Trzy niedokończone rzeczy zamiast jednej ukończonej.',
    work_pattern_en: 'Singular when focused. Scattered when chasing too many transformations at once.',
    work_pattern_pl: 'Wyjątkowy w skupieniu. Rozproszony, gdy ściga zbyt wiele transformacji naraz.',
    relationship_pattern_en: 'You see people\'s potential so clearly that sometimes you love who they could be more than who they are.',
    relationship_pattern_pl: 'Widzisz potencjał ludzi tak wyraźnie, że czasem kochasz ich, którymi mogliby być, bardziej niż tych, którymi są.',
    hidden_fear_en: 'That after all the transformation, the raw material was fine to begin with.',
    hidden_fear_pl: 'Że po całej transformacji surowy materiał był dobry od samego początku.',
    premium_teaser_en: 'Your profile shows what you are actually trying to transform — and whether the target is external or internal.',
    premium_teaser_pl: 'Twój profil pokazuje, co naprawdę próbujesz przekształcić — i czy celem jest coś zewnętrznego, czy wewnętrznego.',
  },

  dreamer: {
    id: 'dreamer',
    name_en: 'The Dreamer',
    name_pl: 'Marzyciel',
    short_hook_en: 'You do not make promises carelessly. Not everyone in your life has learned this about you yet.',
    short_hook_pl: 'Nie składasz obietnic lekkomyślnie. Nie wszyscy w twoim życiu jeszcze to wiedzą.',
    first_signal_en: 'You already know how long this will actually take.',
    first_signal_pl: 'Już wiesz, jak długo to naprawdę zajmie.',
    core_drive_en: 'Things worth building are worth building correctly. This takes longer than people think.',
    core_drive_pl: 'Rzeczy warte zbudowania są warte zbudowania poprawnie. To zajmuje więcej czasu, niż ludzie myślą.',
    strength_en: 'You finish what others abandon when it gets hard.',
    strength_pl: 'Kończysz to, co inni porzucają, gdy robi się trudno.',
    shadow_en: 'You hold on to the plan when the plan has stopped serving you.',
    shadow_pl: 'Trzymasz się planu, gdy plan przestał ci służyć.',
    under_pressure_en: 'You become methodical to the point of rigidity. The method becomes the goal.',
    under_pressure_pl: 'Stajesz się metodyczny do granic sztywności. Metoda staje się celem.',
    work_pattern_en: 'Thorough, high-quality output. Not built for pivoting.',
    work_pattern_pl: 'Dokładne, wysokiej jakości wyniki. Nie stworzony do zmiany kierunku.',
    relationship_pattern_en: 'Reliable in ways that people take for granted until they experience someone who is not.',
    relationship_pattern_pl: 'Niezawodny w sposób, który ludzie traktują jako oczywisty, dopóki nie spotkają kogoś niezawodnego.',
    hidden_fear_en: 'That all the steady progress was in the wrong direction and it is now too late to change.',
    hidden_fear_pl: 'Że cały ten stabilny postęp był w złym kierunku i teraz jest za późno na zmianę.',
    premium_teaser_en: 'Your profile shows the specific axis where your steadiness is a foundation and the one where it has become a trap.',
    premium_teaser_pl: 'Twój profil pokazuje konkretną oś, gdzie twoja stabilność jest fundamentem, i tę, gdzie stała się pułapką.',
  },
};
